name: Run Cypress Tests
on:
  schedule:
    - cron: '55 21 * * *' # run the tests every day at 7:00 AM (UTC)

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress tests
        run: npm run cy:run
